version: '3'

## 9501 暂时没用
services:
  nginx:
    image: nginx
    links:
      - app
    ports:
      - 9501:9501
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: redis
    links:
      - app
    ports:
      - 6379:6379
    # volumes:
      # 持久化 目录映射
      # - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
      # - "./redis/data:/data"
    # command:
      # 执行的命令
      # redis-server /usr/local/etc/redis/redis.conf
  web-server:
    #build: ./web-server
    image: ciandtchina/drupal-web:php7.4-apache-devpack
    volumes:
      - ./source:/var/www/html
      - ./etc/drush:/var/www/html/drush
      #- ./etc/xdebug/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "8088:80"
  database:
    #container_name: database
    image: mysql:5.7.8
    command: mysqld --max_allowed_packet=768M
    expose:
      - "3306"
    environment:
      - MYSQL_PASSWORD=3.1415926
      - MYSQL_ROOT_PASSWORD=3.1415926
      - MYSQL_DATABASE=jaguar_dev
      - MYSQL_USER=jaguar
    volumes:
      - ./persist-data/db-data:/var/lib/mysql
  app:
    image: 03-nginx_app
    #build: .    ## 会执行当前目录下的 Dockerfile
    volumes:
      - ./rootfilesystem/var/www:/var/www
    ports:
      - "9502:9502"
